pipeline {
    agent any

    stages {

        stage('Build Maven (Docker)') {
            steps {
                sh '''
                docker run --rm \
                -v $WORKSPACE/MoodTrackerApp:/app \
                -w /app \
                maven:3.9.6-eclipse-temurin-17 \
                mvn clean package
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t mood-tracker:1.0 .'
            }
        }

        stage('List Images') {
            steps {
                sh 'docker images'
            }
        }
    }
}
